# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'servo_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 508)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Tiêu đề chính
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 60, 250, 31))
        self.label.setObjectName("label")

        # --- THIẾT LẬP SERVO 1 (RỘNG NHẤT) ---
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 100, 100, 20)) # ***
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(140, 100, 320, 25)) # *** Rộng 500
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setMinimum(0)   # ***
        self.horizontalSlider.setMaximum(180) # ***
        self.horizontalSlider.setValue(90)    # ***

        # --- THIẾT LẬP SERVO 2 ---
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 140, 100, 20)) # *** Căn lề 70, cách dòng 140
        self.label_3.setObjectName("label_3")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(140, 140, 320, 25)) # *** Rộng 320
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_2.setMinimum(0)   # ***
        self.horizontalSlider_2.setMaximum(180) # ***
        self.horizontalSlider_2.setValue(90)    # ***

        # --- THIẾT LẬP SERVO 3 ---
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 180, 100, 20)) # *** Căn lề 70, cách dòng 180
        self.label_4.setObjectName("label_4")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(140, 180, 320, 25)) # *** Rộng 320
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_3.setMinimum(0)   # ***
        self.horizontalSlider_3.setMaximum(180) # ***
        self.horizontalSlider_3.setValue(90)    # ***

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        # Kết nối sự kiện in giá trị ra terminal
        self.horizontalSlider.valueChanged.connect(lambda val: print(f"Servo 1: {val}"))
        self.horizontalSlider_2.valueChanged.connect(lambda val: print(f"Servo 2: {val}"))
        self.horizontalSlider_3.valueChanged.connect(lambda val: print(f"Servo 3: {val}"))
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robot Arm Control"))
        self.label.setText(_translate("MainWindow", "SERVO ANGULAR CONTROL"))
        self.label_2.setText(_translate("MainWindow", "SERVO 1"))
        self.label_3.setText(_translate("MainWindow", "SERVO 2"))
        self.label_4.setText(_translate("MainWindow", "SERVO 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())